"""initial governed state for the vertical slice

Revision ID: ba04fd9f1a6b
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ba04fd9f1a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authority_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('granted_authorities', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.String(), nullable=True),
    sa.Column('effective_until', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authority_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authority_relationships_principal_id'), ['principal_id'], unique=False)

    op.create_table('decision_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transition_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('decision_json', sa.Text(), nullable=False),
    sa.Column('kernel_version', sa.String(), nullable=False),
    sa.Column('conformance_spec_version', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('work_request_id', sa.String(), nullable=True),
    sa.Column('work_request_revision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_records_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_transition_id'), ['transition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_work_request_id'), ['work_request_id'], unique=False)

    op.create_table('genesis_record',
    sa.Column('singleton', sa.Integer(), nullable=False),
    sa.Column('deployment_root_fingerprint', sa.String(), nullable=False),
    sa.Column('installer', sa.String(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=False),
    sa.Column('initial_policy_hash', sa.String(), nullable=False),
    sa.Column('initial_config_hash', sa.String(), nullable=False),
    sa.Column('founding_person_id', sa.String(), nullable=False),
    sa.Column('initial_organization_id', sa.String(), nullable=False),
    sa.Column('initial_authority_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.CheckConstraint('singleton = 1', name='ck_genesis_singleton'),
    sa.PrimaryKeyConstraint('singleton')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_by_principal_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_request_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_request_id', sa.String(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('state_revision', sa.String(), nullable=False),
    sa.Column('governance_json', sa.Text(), nullable=False),
    sa.Column('granted_authorities', sa.Text(), nullable=False),
    sa.Column('budget_ceiling_usd', sa.Float(), nullable=True),
    sa.Column('supersedes_revision_id', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.CheckConstraint('revision_number >= 1', name='ck_wrr_number_positive'),
    sa.ForeignKeyConstraint(['work_request_id'], ['work_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_revision', name='uq_wrr_state_revision'),
    sa.UniqueConstraint('work_request_id', 'revision_number', name='uq_wrr_number')
    )
    with op.batch_alter_table('work_request_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_request_revisions_work_request_id'), ['work_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_request_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_request_revisions_work_request_id'))

    op.drop_table('work_request_revisions')
    op.drop_table('work_requests')
    op.drop_table('workspaces')
    op.drop_table('persons')
    op.drop_table('organizations')
    op.drop_table('genesis_record')
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_records_work_request_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_transition_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_outcome'))
        batch_op.drop_index(batch_op.f('ix_decision_records_correlation_id'))

    op.drop_table('decision_records')
    with op.batch_alter_table('authority_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authority_relationships_principal_id'))

    op.drop_table('authority_relationships')
    op.drop_table('agents')
    # ### end Alembic commands ###
