"""Issuer key custody (OD-008, ADR-051): file-based Ed25519 keys.

The honest minimal answer for the first slice: an issuer key is an Ed25519
private key in a PEM file with owner-only permissions, generated by the CLI
below, never generated inside any sign or verify path. HSM/KMS custody,
rotation choreography, and revocation distribution are explicitly out of
scope for the slice and named as follow-up work in ADR-051.

This module is the *only* place in the repository permitted to use randomness,
because key generation is the one act that is nondeterministic by nature.
Signing and verification never come here.

CLI:

    python -m connect_governance.keys generate --out issuer_key.pem
    python -m connect_governance.keys show-public --key issuer_key.pem
"""

from __future__ import annotations

import argparse
import os
import stat
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
    load_pem_private_key,
)

from connect_governance_grants import public_key_id


def generate_key(path: str) -> str:
    """Generate a new Ed25519 issuer key at ``path`` with 0600 permissions.

    Refuses to overwrite an existing file: silently replacing an issuer key
    would orphan every grant it signed, and a fat-fingered rotation must be a
    deliberate act. Returns the new key's identifier.
    """
    if os.path.exists(path):
        raise FileExistsError(
            f"{path} already exists; refusing to overwrite an issuer key"
        )
    key = Ed25519PrivateKey.generate()
    pem = key.private_bytes(
        Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()
    )
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(pem)
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    return public_key_id(show_public_pem(path))


def show_public_pem(path: str) -> str:
    """Read a private key file and return its public key PEM."""
    with open(path, "rb") as f:
        key = load_pem_private_key(f.read(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise ValueError(f"{path} is not an Ed25519 private key")
    return (
        key.public_key()
        .public_bytes(Encoding.PEM, PublicFormat.SubjectPublicKeyInfo)
        .decode("utf-8")
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="connect_governance.keys")
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="generate a new Ed25519 issuer key")
    gen.add_argument("--out", required=True, help="private key output path (0600)")

    show = sub.add_parser("show-public", help="print public key PEM and key id")
    show.add_argument("--key", required=True, help="private key path")

    args = parser.parse_args(argv)
    if args.command == "generate":
        key_id = generate_key(args.out)
        print(f"generated {args.out} (mode 0600)")
        print(f"key id: {key_id}")
        print(f"public key:\n{show_public_pem(args.out)}")
        return 0
    if args.command == "show-public":
        pem = show_public_pem(args.key)
        print(pem)
        print(f"key id: {public_key_id(pem)}")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
